package excel

import (
	"bytes"
	"go/format"
	"text/template"

	"github.com/huandu/xstrings"
)

func genStruct(sheet *Sheet, shouldDisplay func(*Field) bool) (output []byte, err error) {
	var tpl *template.Template
	tmpl := `
package {{.PackageName}}

// {{.Name}} is auto-generated struct
// DO NOT EDIT THIS FILE MANUALLY
// This file is generated by github.com/8liang/kit/excel

type {{capitalize .Name}}Tpl struct {
{{- range .Fields }}
	{{- if visible . }}
	{{- $field := . }}
	{{- if eq .Type "array" }}
		{{- with index .SubFields 0 }}
	{{capitalize $field.Name}} []{{.Type}} {{json $field.Name}}
		{{- end }}
	{{- else if eq .Type "objectArray" }}
	{{capitalize .Name}} []struct {
	{{- range .SubFields }}
		{{- if visible . }}
		{{capitalize .Name}} {{.Type}} {{json .Name}}
		{{- end }}
	{{- end}}
	} {{json .Name}}
	{{- else }}
	{{capitalize .Name}} {{.Type}} {{json .Name}}
	{{- end }}
	{{- end}}
{{- end }}
}`
	if tpl, err = template.New("struct").Funcs(template.FuncMap{
		"capitalize": xstrings.FirstRuneToUpper,
		"json":       func(s string) string { return "`json:\"" + s + "\"`" },
		"visible":    shouldDisplay,
	}).Parse(tmpl); err != nil {
		return
	}
	var buf bytes.Buffer
	if err = tpl.Execute(&buf, sheet); err != nil {
		return
	}
	output, err = format.Source(buf.Bytes())
	return
}

func genInterface(sheet *Sheet, shouldDisplay func(*Field) bool) (output []byte, err error) {
	var tpl *template.Template
	tmpl := `export interface I{{capitalize .Name}}Tpl {
{{- range .Fields }}
 	{{- if visible . }}
	{{- $field := . }}
	{{- if eq .Type "array" }}
	{{- with index .SubFields 0 }}
	{{ .Name }}: Array<{{ resolveTsType .Type }}>
	{{- end }}
	{{- else if eq .Type "objectArray" }}
	{{ $field.Name }}: Array<{
	{{- range .SubFields }}
	{{- if visible . }}
		{{ .Name }}: {{ resolveTsType .Type }}
	{{- end }}
	{{- end }}
	}>
	{{- else }}
	{{ .Name }}: {{ resolveTsType .Type }}
	{{- end }}
	{{- end }}
{{- end }}
}
`
	if tpl, err = template.New("interface").Funcs(template.FuncMap{
		"capitalize":    xstrings.FirstRuneToUpper,
		"resolveTsType": resolveTsType,
		"visible":       shouldDisplay,
	}).Parse(tmpl); err != nil {
		return
	}
	var buf bytes.Buffer
	err = tpl.Execute(&buf, sheet)
	output = buf.Bytes()
	return
}

func resolveTsType(fieldType FieldType) string {
	switch fieldType {
	case FieldTypeInt, FieldTypeFloat:
		return "number"
	default:
		return "string"
	}
}

func visible(f *Field) bool {
	return false
}
